import fs from "node:fs"; import os from "node:os"; import path from "node:path"; import crypto from "node:crypto"; import {execFile} from "node:child_process";
export type SandboxOperation="INSPECT"|"JSON_VALIDATE"|"TEXT_ANALYZE"|"RUN_REGISTERED";
export interface SandboxPolicy { network:"DENY"|"ALLOW_AUTHORIZED"; maxRuntimeMs:number; maxOutputBytes:number; maxInputBytes:number; allowFilesystem:"EPHEMERAL_ONLY"; }
export interface SandboxSession {id:string;tabId:string;root:string;createdAt:string;expiresAt:string;state:"EPHEMERAL";policy:SandboxPolicy;}
export interface SandboxResult {ok:boolean;sessionId:string;operation:SandboxOperation;stdout?:string;stderr?:string;result?:unknown;durationMs:number;evidence:{inputSha256:string;outputSha256?:string;network:"DENY"|"ALLOW_AUTHORIZED";filesystem:"EPHEMERAL_ONLY"};error?:string;}
const sessions=new Map<string,SandboxSession>(); const TTL=10*60*1000;
function sandboxBase(){const shm="/dev/shm"; if(fs.existsSync(shm)&&fs.statSync(shm).isDirectory()) return shm; if(process.env.NEXUS_REQUIRE_MEMORY_SANDBOX==="true") throw new Error("Sandbox memory-only requerido pero /dev/shm no está disponible."); return os.tmpdir();}
const sha256=(v:string|Buffer)=>crypto.createHash("sha256").update(v).digest("hex");
export function createSandboxSession(tabId:string,overrides:Partial<SandboxPolicy>={}):SandboxSession{if(!tabId.trim())throw new Error("tabId requerido.");const id=crypto.randomBytes(16).toString("hex"),root=fs.mkdtempSync(path.join(sandboxBase(),`nexus-sbx-${id.slice(0,8)}-`)),now=Date.now();const s={id,tabId,root,createdAt:new Date(now).toISOString(),expiresAt:new Date(now+TTL).toISOString(),state:"EPHEMERAL" as const,policy:{network:"DENY" as const,maxRuntimeMs:5000,maxOutputBytes:256*1024,maxInputBytes:2*1024*1024,allowFilesystem:"EPHEMERAL_ONLY" as const,...overrides}};sessions.set(id,s);return s;}
export function getSandboxSession(id:string){const s=sessions.get(id);if(!s)return; if(Date.parse(s.expiresAt)<=Date.now()){destroySandboxSession(id);return;} return s;}
export function destroySandboxSession(id:string){const s=sessions.get(id);sessions.delete(id);if(!s)return false;try{fs.rmSync(s.root,{recursive:true,force:true});}catch{}return true;}
export function cleanupExpiredSandboxSessions(){for(const [id,s] of sessions)if(Date.parse(s.expiresAt)<=Date.now())destroySandboxSession(id);}
function assertInput(v:string,n:number){if(Buffer.byteLength(v,"utf8")>n)throw new Error("Entrada demasiado grande para el sandbox.");}
export async function executeSandboxOperation(sessionId:string,operation:SandboxOperation,input:string):Promise<SandboxResult>{cleanupExpiredSandboxSessions();const s=getSandboxSession(sessionId);if(!s)throw new Error("Sandbox inexistente o expirado.");assertInput(input,s.policy.maxInputBytes);const started=Date.now();let result:unknown,stdout="",stderr="",error:string|undefined;
 try{if(operation==="INSPECT")result={bytes:Buffer.byteLength(input),sha256:sha256(input),preview:input.slice(0,2000)};else if(operation==="JSON_VALIDATE"){const v=JSON.parse(input);result={valid:true,type:Array.isArray(v)?"array":typeof v,keys:v&&typeof v==="object"&&!Array.isArray(v)?Object.keys(v).slice(0,100):[]};}else if(operation==="TEXT_ANALYZE")result={characters:input.length,lines:input?input.split(/\r?\n/).length:0,words:input.trim()?input.trim().split(/\s+/).length:0,sha256:sha256(input)};else if(operation==="RUN_REGISTERED"){const helper=path.join(s.root,"registered-task.js");fs.writeFileSync(helper,`const input=process.env.NEXUS_INPUT||"";process.stdout.write(JSON.stringify({bytes:Buffer.byteLength(input),sha256:require('node:crypto').createHash('sha256').update(input).digest('hex')}));`);const child=await new Promise<any>((resolve,reject)=>{const p=execFile(process.execPath,[helper],{cwd:s.root,env:{PATH:process.env.PATH||"",NODE_OPTIONS:"--disallow-code-generation-from-strings",NEXUS_INPUT:input},timeout:s.policy.maxRuntimeMs,maxBuffer:s.policy.maxOutputBytes},(err,out,errOut)=>{if(err&&err.killed)return reject(new Error("Sandbox timeout."));resolve({code:err?(err.code??1):0,out,err:errOut});});p.on("error",reject);});stdout=child.out;stderr=child.err;if(child.code!==0)throw new Error(`Registered task terminó con código ${String(child.code)}.`);result=JSON.parse(stdout);try{fs.rmSync(helper,{force:true});}catch{}}else throw new Error("Operación de sandbox no permitida.");}catch(e:any){error=e?.message||"Sandbox operation failed.";}
 const serialized=result===undefined?"":JSON.stringify(result);return{ok:!error,sessionId,operation,stdout:stdout.slice(0,s.policy.maxOutputBytes),stderr:stderr.slice(0,s.policy.maxOutputBytes),result,durationMs:Date.now()-started,evidence:{inputSha256:sha256(input),outputSha256:serialized?sha256(serialized):undefined,network:s.policy.network,filesystem:s.policy.allowFilesystem},error};}
