import React from "react";
import { Moon, Sun, ShieldCheck, UserCircle, Users, KeyRound, Plug, Plus, Trash2 } from "lucide-react";
import type { ExternalCapability, CapabilityOperation, ExternalCapabilityType } from "../../runtime/capabilities";

export interface NexusSettingsState {
  theme: "light" | "dark";
  allowNetwork: boolean;
  allowExternalPublish: boolean;
  allowPersistentExecution: boolean;
  profileVisible: boolean;
  teamEnabled: boolean;
}

interface Props {
  settings: NexusSettingsState;
  onChange: (next: NexusSettingsState) => void;
  user: any;
  onExportPackage: (passphrase: string) => Promise<void>;
  capabilities: ExternalCapability[];
  onAddCapability: (capability: ExternalCapability) => void;
  onToggleCapability: (id: string) => void;
  onDeleteCapability: (id: string) => void;
}

const OPS: CapabilityOperation[] = ["READ", "PROCESS", "MODIFY", "PERSIST", "EXPORT", "SHARE", "TRAIN", "DERIVE", "EXECUTE"];
const TYPES: ExternalCapabilityType[] = ["model", "api", "sdk", "mcp", "storage", "cloud", "database", "compute", "repository"];

export const NexusSettings: React.FC<Props> = ({ settings, onChange, user, onExportPackage, capabilities, onAddCapability, onToggleCapability, onDeleteCapability }) => {
  const [passphrase, setPassphrase] = React.useState("");
  const [exporting, setExporting] = React.useState(false);
  const [draft, setDraft] = React.useState({ name: "", type: "api" as ExternalCapabilityType, provider: "", endpoint: "", operations: ["READ"] as CapabilityOperation[] });
  const patch = (p: Partial<NexusSettingsState>) => onChange({ ...settings, ...p });
  const exportPackage = async () => { if (!passphrase || exporting) return; setExporting(true); try { await onExportPackage(passphrase); setPassphrase(""); } finally { setExporting(false); } };
  const Toggle = ({ label, value, field }: { label: string; value: boolean; field: keyof NexusSettingsState }) => <button onClick={() => patch({ [field]: !value } as Partial<NexusSettingsState>)} className="w-full flex items-center justify-between border border-slate-200 rounded-xl p-3 text-left"><span className="text-sm font-semibold">{label}</span><span className={`w-10 h-5 rounded-full p-0.5 ${value ? "bg-slate-900" : "bg-slate-300"}`}><span className={`block w-4 h-4 bg-white rounded-full transition-transform ${value ? "translate-x-5" : ""}`} /></span></button>;
  const addCapability = () => { if (!draft.name.trim()) return; onAddCapability({ id: `cap-${Date.now()}`, name: draft.name.trim(), type: draft.type, provider: draft.provider.trim() || undefined, endpoint: draft.endpoint.trim() || undefined, enabled: true, operations: draft.operations, allowedModules: ["create", "analyze", "experiment", "resources", "management", "render"], persistentCredential: false, createdAt: new Date().toISOString() }); setDraft({ name: "", type: "api", provider: "", endpoint: "", operations: ["READ"] }); };
  const toggleOp = (op: CapabilityOperation) => setDraft(prev => ({ ...prev, operations: prev.operations.includes(op) ? prev.operations.filter(x => x !== op) : [...prev.operations, op] }));

  return <div className="space-y-4"><div><h1 className="text-2xl font-black">Ajustes NEXUS™</h1><p className="text-sm text-slate-500 mt-1">Sistema, capacidades externas, autoridad y estado persistente.</p></div>
    <section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><ShieldCheck className="w-5 h-5"/><h2 className="font-bold">Fundamentales</h2></div><div className="space-y-3 text-sm"><blockquote className="border-l-4 border-slate-900 pl-4 font-semibold">“Nada es perfecto. Avanzamos compartiendo lo bueno.”</blockquote><blockquote className="border-l-4 border-slate-300 pl-4 font-semibold">“Una visión clara + interacción estratégica = creación cada vez más certera.”</blockquote><div className="grid md:grid-cols-2 gap-2 text-xs"><div className="border rounded-xl p-3"><b>Conectar ≠ autorizar</b><p className="mt-1 text-slate-500">Una credencial no concede autoridad global.</p></div><div className="border rounded-xl p-3"><b>Pestañas aisladas</b><p className="mt-1 text-slate-500">El usuario es el puente explícito entre contextos.</p></div><div className="border rounded-xl p-3"><b>Ejecutar ≠ guardar</b><p className="mt-1 text-slate-500">El estado temporal no se vuelve persistente sin acción explícita.</p></div><div className="border rounded-xl p-3"><b>Guardar ≠ publicar</b><p className="mt-1 text-slate-500">PKG interno y MVP externo tienen gates distintos.</p></div></div></div></section>

    <div className="grid lg:grid-cols-2 gap-4"><section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><Sun className="w-4 h-4"/><Moon className="w-4 h-4"/><h2 className="font-bold">Sistema</h2></div><div className="flex gap-2"><button onClick={() => patch({theme:"light"})} className={`flex-1 p-3 rounded-xl border text-sm font-bold ${settings.theme === "light" ? "bg-slate-900 text-white" : "border-slate-200"}`}>Claro</button><button onClick={() => patch({theme:"dark"})} className={`flex-1 p-3 rounded-xl border text-sm font-bold ${settings.theme === "dark" ? "bg-slate-900 text-white" : "border-slate-200"}`}>Oscuro</button></div></section><section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><UserCircle className="w-5 h-5"/><h2 className="font-bold">Perfil</h2></div><div className="text-sm font-semibold">{user?.displayName || "Usuario local"}</div><div className="text-xs text-slate-500 mt-1">{user?.email || "Sin cuenta sincronizada"}</div><div className="text-[11px] font-mono mt-3 p-2 bg-slate-50 rounded-lg break-all">identity: {user?.uid || "local-profile"}</div><div className="mt-3"><Toggle label="Permitir visibilidad de perfil en equipos" value={settings.profileVisible} field="profileVisible" /></div></section></div>

    <section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><Plug className="w-5 h-5"/><h2 className="font-bold">Capacidades externas</h2></div><p className="text-xs text-slate-500 mb-3">Registra modelos, APIs, SDKs, MCP, storage, cloud y compute. Registrar una capacidad no la autoriza para una operación concreta.</p><div className="grid lg:grid-cols-2 gap-4"><div className="border border-slate-200 rounded-xl p-4"><input value={draft.name} onChange={e => setDraft({...draft,name:e.target.value})} className="w-full border rounded-xl px-3 py-2 text-sm" placeholder="Nombre de la capacidad"/><div className="grid grid-cols-2 gap-2 mt-2"><select value={draft.type} onChange={e => setDraft({...draft,type:e.target.value as ExternalCapabilityType})} className="border rounded-xl px-3 py-2 text-sm">{TYPES.map(t => <option key={t}>{t}</option>)}</select><input value={draft.provider} onChange={e => setDraft({...draft,provider:e.target.value})} className="border rounded-xl px-3 py-2 text-sm" placeholder="Proveedor"/></div><input value={draft.endpoint} onChange={e => setDraft({...draft,endpoint:e.target.value})} className="mt-2 w-full border rounded-xl px-3 py-2 text-sm" placeholder="Endpoint / referencia (opcional)"/><div className="mt-3 flex flex-wrap gap-1.5">{OPS.map(op => <button key={op} onClick={() => toggleOp(op)} className={`px-2 py-1 rounded-lg text-[10px] font-mono border ${draft.operations.includes(op) ? "bg-slate-900 text-white border-slate-900" : "border-slate-200"}`}>{op}</button>)}</div><button onClick={addCapability} className="mt-3 inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-bold"><Plus className="w-4 h-4"/> Registrar capacidad</button></div><div className="space-y-2">{capabilities.map(c => <div key={c.id} className="border border-slate-200 rounded-xl p-3"><div className="flex items-center justify-between gap-2"><div><div className="font-bold text-sm">{c.name}</div><div className="text-[10px] text-slate-500 font-mono">{c.type}{c.provider ? ` · ${c.provider}` : ""}</div></div><div className="flex items-center gap-1"><button onClick={() => onToggleCapability(c.id)} className={`text-[10px] px-2 py-1 rounded ${c.enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{c.enabled ? "HABILITADA" : "PAUSADA"}</button><button onClick={() => onDeleteCapability(c.id)} className="p-1 rounded hover:bg-rose-50 text-rose-600"><Trash2 className="w-3.5 h-3.5"/></button></div></div><div className="mt-2 flex flex-wrap gap-1">{c.operations.map(op => <span key={op} className="text-[9px] font-mono border rounded px-1.5 py-0.5">{op}</span>)}</div><div className="mt-2 text-[10px] text-slate-500">Módulos: {c.allowedModules.join(", ")}</div></div>)}{capabilities.length === 0 && <div className="border border-dashed rounded-xl p-6 text-xs text-slate-500 text-center">No hay capacidades registradas.</div>}</div></div></section>

    <section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><KeyRound className="w-5 h-5"/><h2 className="font-bold">Permisos y frontera exterior</h2></div><div className="grid gap-2"><Toggle label="Permitir acceso de red dentro del runtime" value={settings.allowNetwork} field="allowNetwork"/><Toggle label="Permitir ejecución persistente" value={settings.allowPersistentExecution} field="allowPersistentExecution"/><Toggle label="Permitir solicitud de publicación externa" value={settings.allowExternalPublish} field="allowExternalPublish"/></div></section>

    <section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><KeyRound className="w-5 h-5"/><h2 className="font-bold">Respaldo interno</h2></div><p className="text-xs text-slate-500">El <span className="font-mono">.nexus.pkg</span> es respaldo/estado interno cifrado. No es el MVP de salida.</p><div className="flex gap-2 mt-3"><input type="password" value={passphrase} onChange={e => setPassphrase(e.target.value)} placeholder="Passphrase del paquete" className="flex-1 border border-slate-200 rounded-xl px-3 py-2 text-sm"/><button onClick={exportPackage} disabled={!passphrase || exporting} className="px-4 py-2 bg-slate-900 text-white rounded-xl text-sm font-bold disabled:opacity-40">{exporting ? "Guardando…" : "Guardar PKG"}</button></div></section>

    <section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><Users className="w-5 h-5"/><h2 className="font-bold">Colaboración</h2></div><Toggle label="Habilitar colaboración en proyectos" value={settings.teamEnabled} field="teamEnabled"/><p className="text-xs text-slate-500 mt-3">La colaboración debe conceder capacidades sobre recursos concretos, no acceso global.</p></section>
  </div>;
};
